language: ruby
rvm:
  - 2.1.0
branches:
  only:
    - develop
    - master
before_script:
  - psql -c 'create database test;' -U postgres
  - python manage.py --value localhost hostname
  - python manage.py secret
  - rake db:reset
