apiVersion: v1
kind: Service
metadata:
  labels:
    name: labdb-web
  name: labdb-web
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30080
      protocol: TCP
  selector:
    name: labdb-web
