apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: postgres
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres
        gcePersistentDisk:
          pdName: postgres
          fsType: ext4
